package com.mustever.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseVideo<M extends BaseVideo<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setAuthor(java.lang.String author) {
		set("author", author);
		return (M)this;
	}
	
	public java.lang.String getAuthor() {
		return getStr("author");
	}

	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public M setLevel(java.lang.String level) {
		set("level", level);
		return (M)this;
	}
	
	public java.lang.String getLevel() {
		return getStr("level");
	}

	public M setCourse(java.lang.String course) {
		set("course", course);
		return (M)this;
	}
	
	public java.lang.String getCourse() {
		return getStr("course");
	}

	public M setTitle(java.lang.String title) {
		set("title", title);
		return (M)this;
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public M setInfo(java.lang.String info) {
		set("info", info);
		return (M)this;
	}
	
	public java.lang.String getInfo() {
		return getStr("info");
	}

	public M setVideoUrl(java.lang.String videoUrl) {
		set("video_url", videoUrl);
		return (M)this;
	}
	
	public java.lang.String getVideoUrl() {
		return getStr("video_url");
	}

	public M setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
		return (M)this;
	}
	
	public java.lang.String getImageUrl() {
		return getStr("image_url");
	}

	public M setEye(java.lang.Integer eye) {
		set("eye", eye);
		return (M)this;
	}
	
	public java.lang.Integer getEye() {
		return getInt("eye");
	}

	public M setComment(java.lang.Integer comment) {
		set("comment", comment);
		return (M)this;
	}
	
	public java.lang.Integer getComment() {
		return getInt("comment");
	}

	public M setHeart(java.lang.Integer heart) {
		set("heart", heart);
		return (M)this;
	}
	
	public java.lang.Integer getHeart() {
		return getInt("heart");
	}

	public M setTags(java.lang.String tags) {
		set("tags", tags);
		return (M)this;
	}
	
	public java.lang.String getTags() {
		return getStr("tags");
	}

	public M setDate(java.util.Date date) {
		set("date", date);
		return (M)this;
	}
	
	public java.util.Date getDate() {
		return get("date");
	}

}
